# Generated by Django 4.2.6 on 2023-11-30 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='Comments',
        ),
        migrations.AlterModelTable(
            name='game',
            table='Games',
        ),
        migrations.AlterModelTable(
            name='review',
            table='Reviews',
        ),
    ]
